'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.XtraBars.TileControlDemo.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.XtraBars.TileControlDemo.Properties.Resources).Assembly)
                    DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Background As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Background", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Calendar As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Calendar", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Camera As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Camera", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Finances As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Finances", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Foods_Slide1 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Foods_Slide1", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property FoodsDrink As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("FoodsDrink", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Game As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Game", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Games As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Games", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property HealthFitnes_Slide1 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("HealthFitnes_Slide1", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property HealthFitness As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("HealthFitness", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property HelpTips As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("HelpTips", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property InternetExplorer As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("InternetExplorer", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Mail As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Mail", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Maps As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Maps", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Music As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Music", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property News As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("News", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property People As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("People", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Photos As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Photos", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ReadingList As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("ReadingList", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property SkyDrive As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("SkyDrive", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Sports As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Sports", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Store As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Store", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Travel As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Travel", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Video As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Video", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Weather As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraBars.TileControlDemo.Properties.Resources.ResourceManager.GetObject("Weather", DevExpress.XtraBars.TileControlDemo.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
