'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.HTML.Demos.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.HTML.Demos.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.HTML.Demos.Properties.Resources).Assembly)
                    DevExpress.HTML.Demos.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.HTML.Demos.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.HTML.Demos.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.HTML.Demos.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property _checked As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.HTML.Demos.Properties.Resources.ResourceManager.GetObject("checked", DevExpress.HTML.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property _unchecked As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.HTML.Demos.Properties.Resources.ResourceManager.GetObject("unchecked", DevExpress.HTML.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property customerquicklocations As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.HTML.Demos.Properties.Resources.ResourceManager.GetObject("customerquicklocations", DevExpress.HTML.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Location As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.HTML.Demos.Properties.Resources.ResourceManager.GetObject("Location", DevExpress.HTML.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property meeting As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.HTML.Demos.Properties.Resources.ResourceManager.GetObject("meeting", DevExpress.HTML.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to &lt; div class=&apos; page theme&apos; &gt; 
        '''    &lt; div class=&apos; form&apos; &gt; 
        '''        &lt; div class=&apos; caption&apos; &gt; 
        '''            Login Form
        '''        &lt; /div&gt; 
        '''        &lt; div class=&apos; content&apos; &gt; 
        '''            &lt; div class=&apos; tab-bar&apos; &gt; 
        '''                &lt; div class=&apos; button tab-button normal&apos;  id=&apos; login&apos; &gt; 
        '''                    LOGIN
        '''                &lt; /div&gt; 
        '''                &lt; div class=&apos; button tab-button highlight&apos; &gt; 
        '''                    SIGN UP
        '''                &lt; /div&gt; 
        '''            &lt; /div&gt; 
        '''            &lt; div class=&apos; default-avatar-container&apos;  hidden=&apos; ${HasPhoto}&apos; &gt; 
        '''   [rest of string was truncated]&quot; ;.
        ''' </summary>
        Friend Shared ReadOnly Property SignUpTemplate As String
            Get
                Return DevExpress.HTML.Demos.Properties.Resources.ResourceManager.GetString("SignUpTemplate", DevExpress.HTML.Demos.Properties.Resources.resourceCulture)
            End Get
        End Property
    End Class
End Namespace
