'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.XtraScheduler.Demos.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.XtraScheduler.Demos.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.XtraScheduler.Demos.Properties.Resources).Assembly)
                    DevExpress.XtraScheduler.Demos.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.XtraScheduler.Demos.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Calendar As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Calendar", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Delete As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Delete", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Delete1 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Delete1", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Down As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Down", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Export As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Export", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Export1 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Export1", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property HighImportance As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("HighImportance", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icon_fittopage_16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("icon_fittopage_16", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icon_page_next_16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("icon_page_next_16", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icon_page_prev_16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("icon_page_prev_16", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icon_pages_16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("icon_pages_16", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icon_print_42x40 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("icon_print_42x40", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property LowImportance As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("LowImportance", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Overview_Buy_Normal As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Overview_Buy_Normal", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Overview_Getting_Started_Normal As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Overview_Getting_Started_Normal", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Overview_Logo As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Overview_Logo", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Overview_Support_Normal As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Overview_Support_Normal", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property [Private] As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Private", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Recurrence As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Recurrence", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property ResetChanges As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("ResetChanges", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Save As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Save", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property SaveAndClose2 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("SaveAndClose2", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_Categorize As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_Categorize", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_Forward As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_Forward", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_Import As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_Import", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_Next7Days As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_Next7Days", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_OutlookImport As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_OutlookImport", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_Print As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_Print", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_Properties As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_Properties", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_ResetView As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_ResetView", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_TimeZones As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_TimeZones", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Scheduler_ViewSettings As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Scheduler_ViewSettings", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_calendar As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_calendar", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_dayonepage As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_dayonepage", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_memo As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_memo", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_monthonepage As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_monthonepage", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_monthtwopage As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_monthtwopage", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_trifold As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_trifold", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_weeklefttorightonepage As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_weeklefttorightonepage", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_weeklefttorightwopage As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_weeklefttorightwopage", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_weekonepage As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_weekonepage", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property small_weektwopage As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("small_weektwopage", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property UISuperHero As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("UISuperHero", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Up As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("Up", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property ViewSetting As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraScheduler.Demos.Properties.Resources.ResourceManager.GetObject("ViewSetting", DevExpress.XtraScheduler.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
    End Class
End Namespace
