'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.DemoReports

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class SvgResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.DemoReports.SvgResources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DevExpress.DemoReports.SvgResources", GetType(DevExpress.DemoReports.SvgResources).Assembly)
                    DevExpress.DemoReports.SvgResources.resourceMan = temp
                End If

                Return DevExpress.DemoReports.SvgResources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.DemoReports.SvgResources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.DemoReports.SvgResources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Check_Green As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Check_Green", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Check_Grey As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Check_Grey", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Check_Off As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Check_Off", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Check_On As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Check_On", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Cross_Grey As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Cross_Grey", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Cross_Red As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Cross_Red", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Neutral_Grey As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Neutral_Grey", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Neutral_Yellow As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Neutral_Yellow", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Sad_Grey As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Sad_Grey", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Sad_Red As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Sad_Red", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Smile_Green As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Smile_Green", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Smile_Grey As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Smile_Grey", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Warning_Grey As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Warning_Grey", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Byte[].
        ''' </summary>
        Friend Shared ReadOnly Property Warning_Yellow As Byte()
            Get
                Dim obj As Object = DevExpress.DemoReports.SvgResources.ResourceManager.GetObject("Warning_Yellow", DevExpress.DemoReports.SvgResources.resourceCulture)
                Return CType((obj), Byte())
            End Get
        End Property
    End Class
End Namespace
