using System.Data;
using System.Drawing;
using DevExpress.Utils;

namespace DevExpress.XtraMap.Demos {

    public partial class VectorItemDataSource : FooteredMapTutorialControl {
        Font toolTipFont;

        Font ToolTipFont {
            get {
                if(toolTipFont == null)
                    toolTipFont = new Font(AppearanceObject.DefaultFont.FontFamily, 12, FontStyle.Bold);
                return toolTipFont;
            }
        }

        public override MapControl MapControl { get { return mapControl1; } }
        protected override Image CopyrightImage { get { return DemoUtils.AzureLogo; } }
        protected override string CopyrightText { get { return DemoUtils.AzureCopyright; } }

        public VectorItemDataSource() {
            InitializeComponent();
            DemoUtils.SetAzureMapDataProviderKey(AzureImageryMapDataProvider);
            DemoUtils.SetAzureMapDataProviderKey(AzureLabelsMapDataProvider);
            DemoUtils.SetAzureMapDataProviderKey(MiniMapDataProvider);

            // This line of code is generated by Data Source Configuration Wizard
            // Create a new DataSet
            System.Data.DataSet xmlDataSet = new System.Data.DataSet("XML DataSet");
            // Load the XML document to the DataSet
            xmlDataSet.ReadXml(DemoUtils.GetRelativePath("Ships.xml"));
            // This line of code is generated by Data Source Configuration Wizard
            DataTable ships = xmlDataSet.Tables["Ship"];
            ListSourceDataAdapter.DataSource = ships;
            MiniMapDataAdapter.DataSource = ships;
        }
        string MakeTitle(DataRowView dataRowView) {
            return dataRowView["Name"].ToString() + " (" + dataRowView["Year"].ToString() + ")";
        }
        void toolTipController1_BeforeShow(object sender, ToolTipControllerShowEventArgs e) {
            MapCustomElement customElement = (MapCustomElement)(e.SelectedObject);
            DataRowView sourceItem = (DataRowView)ItemsLayer.GetItemSourceObject(customElement);

            ToolTipTitleItem titleItem1 = new ToolTipTitleItem() { Text = MakeTitle(sourceItem) };
            titleItem1.Appearance.ForeColor = SystemColors.GrayText;
            titleItem1.Appearance.Font = ToolTipFont;

            SuperToolTip superToolTip = new SuperToolTip();
            superToolTip.Items.Add(titleItem1);

            ToolTipSeparatorItem sepItem = new ToolTipSeparatorItem();
            superToolTip.Items.Add(sepItem);

            ToolTipItem textItem = new ToolTipItem() { Text = e.ToolTip };
            superToolTip.Items.Add(textItem);
            e.SuperTip = superToolTip;
        }
        void OnDispose(bool disposing) {
            if(toolTipFont != null) {
                toolTipFont.Dispose();
                toolTipFont = null;
            }
        }
        protected override void InitRibbon() {
            base.InitRibbon();
            DisableZoomOptions();
        }
        protected override void ChangeEnableNavigation(bool enable) {
            MapControl.EnableScrolling = enable;
        }
    }
}
