'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace XtraReportsDemos.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(XtraReportsDemos.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(XtraReportsDemos.Properties.Resources).Assembly)
                    XtraReportsDemos.Properties.Resources.resourceMan = temp
                End If

                Return XtraReportsDemos.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return XtraReportsDemos.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                XtraReportsDemos.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        ''' </summary>
        Friend Shared ReadOnly Property AppIcon As System.Drawing.Icon
            Get
                Dim obj As Object = XtraReportsDemos.Properties.Resources.ResourceManager.GetObject("AppIcon", XtraReportsDemos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Icon)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property continent As System.Drawing.Bitmap
            Get
                Dim obj As Object = XtraReportsDemos.Properties.Resources.ResourceManager.GetObject("continent", XtraReportsDemos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fswiss\fprq2\fcharset0 Tahoma;}{\f1\fnil\fprq2\fcharset2 Wingdings;}{\f2\fswiss\fcharset0 Arial;}}
        ''' {\colortbl ;\red0\green0\blue0;}
        ''' {\*\generator Msftedit 5.41.15.1507;}\viewkind4\uc1\pard\nowidctlpar\sb100\sa120\lang1033\b\f0\fs22 XtraReports Suite Main Features\par
        ''' \pard\nowidctlpar\fi-360\li720\sb100\sa120\tx720\b0\f1\fs20\&apos; fc\tab\b\f0 Windows Forms and ASP.NET\b0  - XtraReports works both in Windows Forms projects and ASP .NET applications. You c [rest of string was truncated]&quot; ;.
        ''' </summary>
        Friend Shared ReadOnly Property ReportsAbout As String
            Get
                Return XtraReportsDemos.Properties.Resources.ResourceManager.GetString("ReportsAbout", XtraReportsDemos.Properties.Resources.resourceCulture)
            End Get
        End Property
    End Class
End Namespace
