'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.XtraDialogs.Demos.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.XtraDialogs.Demos.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.XtraDialogs.Demos.Properties.Resources).Assembly)
                    DevExpress.XtraDialogs.Demos.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.XtraDialogs.Demos.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property car As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("car", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property database As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("database", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property f3 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("f3", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property f4 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("f4", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property f5 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("f5", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property f6 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("f6", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property f7 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("f7", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property f8 As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("f8", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property folder As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("folder", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property navigateBack As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("navigateBack", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property navigateForward As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("navigateForward", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property navigateUp As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("navigateUp", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property network As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("network", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property open As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("open", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property save As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraDialogs.Demos.Properties.Resources.ResourceManager.GetObject("save", DevExpress.XtraDialogs.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
    End Class
End Namespace
