'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
' 
' This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
' 
Imports System.Diagnostics
Imports System.ComponentModel
Imports System
Imports System.Xml.Serialization
#If Not NET
Imports System.Web.Services
Imports System.Web.Services.Protocols

Namespace DevExpress.XtraGauges.Demos.net.webservicex.www

    ''' <remarks/> 
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>
    <System.Diagnostics.DebuggerStepThroughAttribute()>
    <System.ComponentModel.DesignerCategoryAttribute("code")>
    <WebServiceBindingAttribute(Name:="WeatherForecastSoap", [Namespace]:="http://www.webservicex.net")>
    Public Partial Class WeatherForecast
        Inherits SoapHttpClientProtocol

        Private GetWeatherByZipCodeOperationCompleted As Threading.SendOrPostCallback

        Private GetWeatherByPlaceNameOperationCompleted As Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean

        ''' <remarks/> 
        Public Sub New()
            Url = Global.DevExpress.XtraGauges.Demos.Properties.Settings.Default.GaugesMainDemo_net_webservicex_www_WeatherForecast
            If IsLocalFileSystemWebService(Url) = True Then
                UseDefaultCredentials = True
                useDefaultCredentialsSetExplicitly = False
            Else
                useDefaultCredentialsSetExplicitly = True
            End If
        End Sub

        Public Overloads Property Url As String
            Get
                Return MyBase.Url
            End Get

            Set(ByVal value As String)
                If IsLocalFileSystemWebService(MyBase.Url) = True AndAlso useDefaultCredentialsSetExplicitly = False AndAlso IsLocalFileSystemWebService(value) = False Then
                    MyBase.UseDefaultCredentials = False
                End If

                MyBase.Url = value
            End Set
        End Property

        Public Overloads Property UseDefaultCredentials As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get

            Set(ByVal value As Boolean)
                MyBase.UseDefaultCredentials = value
                useDefaultCredentialsSetExplicitly = True
            End Set
        End Property

        ''' <remarks/> 
        Public Event GetWeatherByZipCodeCompleted As GetWeatherByZipCodeCompletedEventHandler

        ''' <remarks/> 
        Public Event GetWeatherByPlaceNameCompleted As GetWeatherByPlaceNameCompletedEventHandler

        ''' <remarks/> 
        <SoapDocumentMethodAttribute("http://www.webservicex.net/GetWeatherByZipCode", RequestNamespace:="http://www.webservicex.net", ResponseNamespace:="http://www.webservicex.net", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=SoapParameterStyle.Wrapped)>
        Public Function GetWeatherByZipCode(ByVal ZipCode As String) As WeatherForecasts
            Dim results As Object() = Invoke("GetWeatherByZipCode", New Object() {ZipCode})
            Return CType(results(0), WeatherForecasts)
        End Function

        ''' <remarks/> 
        Public Sub GetWeatherByZipCodeAsync(ByVal ZipCode As String)
            GetWeatherByZipCodeAsync(ZipCode, Nothing)
        End Sub

        ''' <remarks/> 
        Public Sub GetWeatherByZipCodeAsync(ByVal ZipCode As String, ByVal userState As Object)
            If GetWeatherByZipCodeOperationCompleted Is Nothing Then
                GetWeatherByZipCodeOperationCompleted = New Threading.SendOrPostCallback(AddressOf OnGetWeatherByZipCodeOperationCompleted)
            End If

            InvokeAsync("GetWeatherByZipCode", New Object() {ZipCode}, GetWeatherByZipCodeOperationCompleted, userState)
        End Sub

        Private Sub OnGetWeatherByZipCodeOperationCompleted(ByVal arg As Object)
            If GetWeatherByZipCodeCompletedEvent IsNot Nothing Then
                Dim invokeArgs As InvokeCompletedEventArgs = CType(arg, InvokeCompletedEventArgs)
                RaiseEvent GetWeatherByZipCodeCompleted(Me, New GetWeatherByZipCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        ''' <remarks/> 
        <SoapDocumentMethodAttribute("http://www.webservicex.net/GetWeatherByPlaceName", RequestNamespace:="http://www.webservicex.net", ResponseNamespace:="http://www.webservicex.net", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=SoapParameterStyle.Wrapped)>
        Public Function GetWeatherByPlaceName(ByVal PlaceName As String) As WeatherForecasts
            Dim results As Object() = Invoke("GetWeatherByPlaceName", New Object() {PlaceName})
            Return CType(results(0), WeatherForecasts)
        End Function

        ''' <remarks/> 
        Public Sub GetWeatherByPlaceNameAsync(ByVal PlaceName As String)
            GetWeatherByPlaceNameAsync(PlaceName, Nothing)
        End Sub

        ''' <remarks/> 
        Public Sub GetWeatherByPlaceNameAsync(ByVal PlaceName As String, ByVal userState As Object)
            If GetWeatherByPlaceNameOperationCompleted Is Nothing Then
                GetWeatherByPlaceNameOperationCompleted = New Threading.SendOrPostCallback(AddressOf OnGetWeatherByPlaceNameOperationCompleted)
            End If

            InvokeAsync("GetWeatherByPlaceName", New Object() {PlaceName}, GetWeatherByPlaceNameOperationCompleted, userState)
        End Sub

        Private Sub OnGetWeatherByPlaceNameOperationCompleted(ByVal arg As Object)
            If GetWeatherByPlaceNameCompletedEvent IsNot Nothing Then
                Dim invokeArgs As InvokeCompletedEventArgs = CType(arg, InvokeCompletedEventArgs)
                RaiseEvent GetWeatherByPlaceNameCompleted(Me, New GetWeatherByPlaceNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        ''' <remarks/> 
        Public Overloads Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If Equals(url, Nothing) OrElse Equals(url, String.Empty) Then
                Return False
            End If

            Dim wsUri As Uri = New Uri(url)
            If wsUri.Port >= 1024 AndAlso String.Compare(wsUri.Host, "localHost", StringComparison.OrdinalIgnoreCase) = 0 Then
                Return True
            End If

            Return False
        End Function
    End Class

#End If
    ''' <remarks/> 
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")>
    <SerializableAttribute()>
    <System.Diagnostics.DebuggerStepThroughAttribute()>
    <System.ComponentModel.DesignerCategoryAttribute("code")>
    <XmlTypeAttribute([Namespace]:="http://www.webservicex.net")>
    Public Partial Class WeatherForecasts

        Private latitudeField As Single

        Private longitudeField As Single

        Private allocationFactorField As Single

        Private fipsCodeField As String

        Private placeNameField As String

        Private stateCodeField As String

        Private statusField As String

        Private detailsField As WeatherData()

        ''' <remarks/> 
        Public Property Latitude As Single
            Get
                Return latitudeField
            End Get

            Set(ByVal value As Single)
                latitudeField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property Longitude As Single
            Get
                Return longitudeField
            End Get

            Set(ByVal value As Single)
                longitudeField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property AllocationFactor As Single
            Get
                Return allocationFactorField
            End Get

            Set(ByVal value As Single)
                allocationFactorField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property FipsCode As String
            Get
                Return fipsCodeField
            End Get

            Set(ByVal value As String)
                fipsCodeField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property PlaceName As String
            Get
                Return placeNameField
            End Get

            Set(ByVal value As String)
                placeNameField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property StateCode As String
            Get
                Return stateCodeField
            End Get

            Set(ByVal value As String)
                stateCodeField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property Status As String
            Get
                Return statusField
            End Get

            Set(ByVal value As String)
                statusField = value
            End Set
        End Property

        ''' <remarks/> 
        <XmlArrayItemAttribute(IsNullable:=False)>
        Public Property Details As WeatherData()
            Get
                Return detailsField
            End Get

            Set(ByVal value As WeatherData())
                detailsField = value
            End Set
        End Property
    End Class

    ''' <remarks/> 
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")>
    <SerializableAttribute()>
    <System.Diagnostics.DebuggerStepThroughAttribute()>
    <System.ComponentModel.DesignerCategoryAttribute("code")>
    <XmlTypeAttribute([Namespace]:="http://www.webservicex.net")>
    Public Partial Class WeatherData

        Private dayField As String

        Private weatherImageField As String

        Private maxTemperatureFField As String

        Private minTemperatureFField As String

        Private maxTemperatureCField As String

        Private minTemperatureCField As String

        ''' <remarks/> 
        Public Property Day As String
            Get
                Return dayField
            End Get

            Set(ByVal value As String)
                dayField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property WeatherImage As String
            Get
                Return weatherImageField
            End Get

            Set(ByVal value As String)
                weatherImageField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property MaxTemperatureF As String
            Get
                Return maxTemperatureFField
            End Get

            Set(ByVal value As String)
                maxTemperatureFField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property MinTemperatureF As String
            Get
                Return minTemperatureFField
            End Get

            Set(ByVal value As String)
                minTemperatureFField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property MaxTemperatureC As String
            Get
                Return maxTemperatureCField
            End Get

            Set(ByVal value As String)
                maxTemperatureCField = value
            End Set
        End Property

        ''' <remarks/> 
        Public Property MinTemperatureC As String
            Get
                Return minTemperatureCField
            End Get

            Set(ByVal value As String)
                minTemperatureCField = value
            End Set
        End Property
    End Class

    ''' <remarks/> 
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>
    Public Delegate Sub GetWeatherByZipCodeCompletedEventHandler(ByVal sender As Object, ByVal e As GetWeatherByZipCodeCompletedEventArgs)

    ''' <remarks/> 
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>
    <System.Diagnostics.DebuggerStepThroughAttribute()>
    <System.ComponentModel.DesignerCategoryAttribute("code")>
    Public Partial Class GetWeatherByZipCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results As Object()

        Friend Sub New(ByVal results As Object(), ByVal exception As Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        ''' <remarks/> 
        Public ReadOnly Property Result As WeatherForecasts
            Get
                RaiseExceptionIfNecessary()
                Return CType(results(0), WeatherForecasts)
            End Get
        End Property
    End Class

    ''' <remarks/> 
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>
    Public Delegate Sub GetWeatherByPlaceNameCompletedEventHandler(ByVal sender As Object, ByVal e As GetWeatherByPlaceNameCompletedEventArgs)

    ''' <remarks/> 
    <CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>
    <System.Diagnostics.DebuggerStepThroughAttribute()>
    <System.ComponentModel.DesignerCategoryAttribute("code")>
    Public Partial Class GetWeatherByPlaceNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results As Object()

        Friend Sub New(ByVal results As Object(), ByVal exception As Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        ''' <remarks/> 
        Public ReadOnly Property Result As WeatherForecasts
            Get
                RaiseExceptionIfNecessary()
                Return CType(results(0), WeatherForecasts)
            End Get
        End Property
    End Class
End Namespace
