Imports System
Imports System.Collections.Generic
Imports System.Drawing
Imports DevExpress.XtraEditors
Imports DevExpress.XtraSplashScreen

Namespace DevExpress.XtraMap.Demos

    Public Partial Class Clustering
        Inherits DevExpress.XtraMap.Demos.FooteredMapTutorialControl

        Private Shared ReadOnly AttributeName As String = "location"

        Private Shared ReadOnly DensityLegendHeader As String = "Tree density"

        Private Shared ReadOnly LocationLegendHeader As String = "Tree location"

        Private clustererField As DevExpress.XtraMap.MapClustererBase

        Private ReadOnly Property Legend As ColorListLegend
            Get
                Return CType((Me.mapControl1.Legends(0)), DevExpress.XtraMap.ColorListLegend)
            End Get
        End Property

        Private Property Clusterer As MapClustererBase
            Get
                Return Me.clustererField
            End Get

            Set(ByVal value As MapClustererBase)
                If Me.clustererField Is value Then Return
                If Me.clustererField IsNot Nothing Then Me.UnsubscribeEvents()
                Me.clustererField = value
                If Me.clustererField IsNot Nothing Then
                    Me.clustererField.StepInPixels = CInt(Me.barStepInPixels.EditValue)
                    Me.SubscribeEvents()
                End If
            End Set
        End Property

        Protected Overrides ReadOnly Property MiniMapAzureKind As AzureTileset
            Get
                Return DevExpress.XtraMap.AzureTileset.BaseRoad
            End Get
        End Property

        Protected Overrides ReadOnly Property MiniMapAlignment As MiniMapAlignment
            Get
                Return DevExpress.XtraMap.MiniMapAlignment.TopLeft
            End Get
        End Property

        Public Overrides ReadOnly Property MapControl As MapControl
            Get
                Return Me.mapControl1
            End Get
        End Property

        Protected Overrides ReadOnly Property CopyrightImage As Image
            Get
                Return DevExpress.XtraMap.Demos.DemoUtils.AzureLogo
            End Get
        End Property

        Protected Overrides ReadOnly Property CopyrightText As String
            Get
                Return DevExpress.XtraMap.Demos.DemoUtils.AzureCopyright
            End Get
        End Property

        Public Sub New()
            Me.InitializeComponent()
            Call DevExpress.XtraMap.Demos.DemoUtils.SetAzureMapDataProviderKey(Me.AzureMapDataProvider)
            Me.UpdateClusterer()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Create a new DataSet
            Dim xmlDataSet As System.Data.DataSet = New System.Data.DataSet("XML DataSet")
            ' Load the XML document to the DataSet
            xmlDataSet.ReadXml(DevExpress.XtraMap.Demos.DemoUtils.GetRelativePath("TreesCl.xml"))
            ' This line of code is generated by Data Source Configuration Wizard
            Me.ListSourceDataAdapter.DataSource = xmlDataSet.Tables("Row")
        End Sub

        Private Function CreateChoroplethColorizer() As MapColorizer
            Dim colorizer As DevExpress.XtraMap.ChoroplethColorizer = New DevExpress.XtraMap.ChoroplethColorizer()
            colorizer.RangeStops.AddRange(New System.Collections.Generic.List(Of Double) From {1, 10, 50, 100, 500, 1000, 2000, 3000, 4000, 5000})
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&H2F, &H3D, &H13)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&H3D, &H4F, &H19)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&H4c, &H64, &H1e)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&H68, &H8a, &H2a)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&H77, &H9e, &H30)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&H8b, &Hb8, &H38)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&H9b, &HcD, &H3e)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&Ha7, &HdD, &H43)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&Hb7, &Hf2, &H49)))
            colorizer.ColorItems.Add(New DevExpress.XtraMap.ColorizerColorItem(System.Drawing.Color.FromArgb(&Hca, &HfF, &H68)))
            colorizer.ValueProvider = New DevExpress.XtraMap.MapClusterValueProvider()
            Me.Legend.Header = DevExpress.XtraMap.Demos.Clustering.DensityLegendHeader
            Return colorizer
        End Function

        Private Function CreateKeyColorColorizer() As MapColorizer
            Dim colorizer As DevExpress.XtraMap.KeyColorColorizer = New DevExpress.XtraMap.KeyColorColorizer()
            colorizer.ItemKeyProvider = New DevExpress.XtraMap.AttributeItemKeyProvider() With {.AttributeName = DevExpress.XtraMap.Demos.Clustering.AttributeName}
            colorizer.PredefinedColorSchema = DevExpress.XtraMap.PredefinedColorSchema.Palette
            Me.Legend.Header = DevExpress.XtraMap.Demos.Clustering.LocationLegendHeader
            Return colorizer
        End Function

        Private Function CreateClusterer() As MapClustererBase
            If Me.chkDistanceBasedClustering.Checked Then Return New DevExpress.XtraMap.DistanceBasedClusterer()
            If Me.chkMarkerClustering.Checked Then Return New DevExpress.XtraMap.MarkerClusterer()
            Return Nothing
        End Function

        Private Sub UpdateClusterer()
            Me.Clusterer = Me.CreateClusterer()
            Me.ItemsLayer.Colorizer = If(Me.chkClusteringByAttr.Checked, Me.CreateKeyColorColorizer(), Me.CreateChoroplethColorizer())
            If Me.Clusterer IsNot Nothing Then
                Me.Clusterer.GroupProvider = If(Me.chkClusteringByAttr.Checked, Me.CreateGroupProvider(), Nothing)
                If Me.chkCustomFactory.Checked Then Me.Clusterer.SetClusterItemFactory(New DevExpress.XtraMap.Demos.CustomClusterFactory())
            End If

            Me.ListSourceDataAdapter.Clusterer = Me.Clusterer
        End Sub

        Private Function CreateGroupProvider() As AttributeGroupProvider
            Return New DevExpress.XtraMap.AttributeGroupProvider() With {.AttributeName = DevExpress.XtraMap.Demos.Clustering.AttributeName}
        End Function

        Private Sub SubscribeEvents()
            AddHandler Me.Clusterer.Clustering, AddressOf Me.Clusterer_OnClustering
            AddHandler Me.Clusterer.Clustered, AddressOf Me.Clusterer_OnClustered
        End Sub

        Private Sub UnsubscribeEvents()
            RemoveHandler Me.Clusterer.Clustering, AddressOf Me.Clusterer_OnClustering
            RemoveHandler Me.Clusterer.Clustered, AddressOf Me.Clusterer_OnClustered
        End Sub

        Private Sub Clusterer_OnClustered(ByVal sender As Object, ByVal e As DevExpress.XtraMap.ClusteredEventArgs)
            If DevExpress.XtraSplashScreen.SplashScreenManager.[Default] IsNot Nothing AndAlso DevExpress.XtraSplashScreen.SplashScreenManager.[Default].IsSplashFormVisible Then Call DevExpress.XtraSplashScreen.SplashScreenManager.CloseDefaultWaitForm()
        End Sub

        Private Sub Clusterer_OnClustering(ByVal sender As Object, ByVal e As System.EventArgs)
            Call DevExpress.XtraSplashScreen.SplashScreenManager.ShowDefaultWaitForm(Me.ParentForm, True, True, "", "Clustering...")
        End Sub

        Private Sub OnRibbonItemClick(ByVal sender As Object, ByVal e As DevExpress.XtraBars.ItemClickEventArgs)
            Me.UpdateClusterer()
        End Sub

        Private Sub OnEditValueChanging(ByVal sender As Object, ByVal e As DevExpress.XtraEditors.Controls.ChangingEventArgs)
            If Me.Clusterer IsNot Nothing Then Me.Clusterer.StepInPixels = CInt(e.NewValue)
        End Sub

        Private Sub mapControl1_MapItemClick(ByVal sender As Object, ByVal e As DevExpress.XtraMap.MapItemClickEventArgs)
            Dim groupItems As System.Collections.Generic.IList(Of DevExpress.XtraMap.MapItem) = e.Item.ClusteredItems
            If groupItems IsNot Nothing Then Me.mapControl1.ZoomToFit(groupItems)
        End Sub

        Private Sub repositoryItemTrackBar1_BeforeShowValueToolTip(ByVal sender As Object, ByVal e As DevExpress.XtraEditors.TrackBarValueToolTipEventArgs)
            Dim trackBar As DevExpress.XtraEditors.TrackBarControl = TryCast(sender, DevExpress.XtraEditors.TrackBarControl)
            If trackBar IsNot Nothing Then e.ShowArgs.ToolTip = String.Format("Step: {0} pixels", trackBar.EditValue)
        End Sub
    End Class

    Public Class CustomClusterFactory
        Inherits DevExpress.XtraMap.DefaultClusterItemFactory

        Protected Overrides Function CreateItemInstance(ByVal obj As System.Collections.Generic.IList(Of DevExpress.XtraMap.MapItem)) As MapItem
            Return New DevExpress.XtraMap.MapCallout()
        End Function
    End Class
End Namespace
