Imports System.Data
Imports System.Drawing
Imports DevExpress.Utils

Namespace DevExpress.XtraMap.Demos

    Public Partial Class VectorItemDataSource
        Inherits FooteredMapTutorialControl

        Private toolTipFontField As Font

        Private ReadOnly Property ToolTipFont As Font
            Get
                If toolTipFontField Is Nothing Then toolTipFontField = New Font(AppearanceObject.DefaultFont.FontFamily, 12, FontStyle.Bold)
                Return toolTipFontField
            End Get
        End Property

        Public Overrides ReadOnly Property MapControl As MapControl
            Get
                Return mapControl1
            End Get
        End Property

        Protected Overrides ReadOnly Property CopyrightImage As Image
            Get
                Return DemoUtils.AzureLogo
            End Get
        End Property

        Protected Overrides ReadOnly Property CopyrightText As String
            Get
                Return DemoUtils.AzureCopyright
            End Get
        End Property

        Public Sub New()
            InitializeComponent()
            DemoUtils.SetAzureMapDataProviderKey(AzureImageryMapDataProvider)
            DemoUtils.SetAzureMapDataProviderKey(AzureLabelsMapDataProvider)
            DemoUtils.SetAzureMapDataProviderKey(MiniMapDataProvider)
            ' This line of code is generated by Data Source Configuration Wizard
            ' Create a new DataSet
            Dim xmlDataSet As DataSet = New DataSet("XML DataSet")
            ' Load the XML document to the DataSet
            xmlDataSet.ReadXml(DemoUtils.GetRelativePath("Ships.xml"))
            ' This line of code is generated by Data Source Configuration Wizard
            Dim ships As DataTable = xmlDataSet.Tables("Ship")
            ListSourceDataAdapter.DataSource = ships
            MiniMapDataAdapter.DataSource = ships
        End Sub

        Private Function MakeTitle(ByVal dataRowView As DataRowView) As String
            Return dataRowView("Name").ToString() & " (" & dataRowView("Year").ToString() & ")"
        End Function

        Private Sub toolTipController1_BeforeShow(ByVal sender As Object, ByVal e As ToolTipControllerShowEventArgs)
            Dim customElement As MapCustomElement = CType(e.SelectedObject, MapCustomElement)
            Dim sourceItem As DataRowView = CType(ItemsLayer.GetItemSourceObject(customElement), DataRowView)
            Dim titleItem1 As ToolTipTitleItem = New ToolTipTitleItem() With {.Text = MakeTitle(sourceItem)}
            titleItem1.Appearance.ForeColor = SystemColors.GrayText
            titleItem1.Appearance.Font = ToolTipFont
            Dim superToolTip As SuperToolTip = New SuperToolTip()
            superToolTip.Items.Add(titleItem1)
            Dim sepItem As ToolTipSeparatorItem = New ToolTipSeparatorItem()
            superToolTip.Items.Add(sepItem)
            Dim textItem As ToolTipItem = New ToolTipItem() With {.Text = e.ToolTip}
            superToolTip.Items.Add(textItem)
            e.SuperTip = superToolTip
        End Sub

        Private Overloads Sub OnDispose(ByVal disposing As Boolean)
            If toolTipFontField IsNot Nothing Then
                toolTipFontField.Dispose()
                toolTipFontField = Nothing
            End If
        End Sub

        Protected Overrides Sub InitRibbon()
            MyBase.InitRibbon()
            DisableZoomOptions()
        End Sub

        Protected Overrides Sub ChangeEnableNavigation(ByVal enable As Boolean)
            MapControl.EnableScrolling = enable
        End Sub
    End Class
End Namespace
