'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.XtraLayout.Demos.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.XtraLayout.Demos.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.XtraLayout.Demos.Properties.Resources).Assembly)
                    DevExpress.XtraLayout.Demos.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.XtraLayout.Demos.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property _1 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("1", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property _2 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("2", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property _3 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("3", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property _4 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("4", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property _5 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("5", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property _6 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("6", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property bc11 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("bc11", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property bc12 As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("bc12", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property Logo As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Logo", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        ''' </summary>
        Friend Shared ReadOnly Property print As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("print", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper0_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper0_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper1_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper1_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper10_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper10_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper12_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper12_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper13_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper13_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper14_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper14_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper15_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper15_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper16_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper16_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper18_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper18_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper19_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper19_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper2_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper2_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper20_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper20_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper21_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper21_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper22_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper22_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper24_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper24_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper25_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper25_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper26_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper26_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper27_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper27_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper28_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper28_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper3_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper3_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper4_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper4_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper6_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper6_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper7_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper7_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper8_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper8_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Striper9_1_ As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.XtraLayout.Demos.Properties.Resources.ResourceManager.GetObject("Striper9_1_", DevExpress.XtraLayout.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
