'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System.Collections.Generic

Namespace DevExpress.XtraPivotGrid.Demos

    Public Partial Class Product

        <System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")>
        Public Sub New()
            Sales = New HashSet(Of Sale)()
        End Sub

        Public Property OID As Integer

        Public Property ProductName As String

        Public Property Category As Integer?

        Public Property OptimisticLockField As Integer?

        Public Property GCRecord As Integer?

        Public Overridable Property Category1 As Category

        <System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")>
        Public Overridable Property Sales As ICollection(Of Sale)
    End Class
End Namespace
