'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.AI.Demos.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.AI.Demos.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.AI.Demos.Properties.Resources).Assembly)
                    DevExpress.AI.Demos.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.AI.Demos.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.AI.Demos.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.AI.Demos.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_assistant_menu As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_assistant_menu", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_assistant_menu_dark As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_assistant_menu_dark", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_expression_Thumb As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_expression_Thumb", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_chatGuide As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_chatGuide", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_chatThumb As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_chatThumb", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_expressionGuide As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_expressionGuide", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_localizationGuide As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_localizationGuide", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_localizationThumb As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_localizationThumb", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_test_dataGuide As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_test_dataGuide", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_test_dataThumb As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_test_dataThumb", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_wizardGuide As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_wizardGuide", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_reports_wizardThumb As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_reports_wizardThumb", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property ai_smart_search As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.AI.Demos.Properties.Resources.ResourceManager.GetObject("ai_smart_search", DevExpress.AI.Demos.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
