'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace DevExpress.RealtorWorld.Win.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(DevExpress.RealtorWorld.Win.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(DevExpress.RealtorWorld.Win.Properties.Resources).Assembly)
                    DevExpress.RealtorWorld.Win.Properties.Resources.resourceMan = temp
                End If

                Return DevExpress.RealtorWorld.Win.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Arrow As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Arrow", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Calc As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Calc", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Home As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Home", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Rates As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Rates", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Research As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Research", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Rotate As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Rotate", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property SmallHome As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("SmallHome", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Statistics As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Statistics", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property System As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("System", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Under_Construction As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("Under_Construction", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property UserManagment As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("UserManagment", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property zillow_logo As System.Drawing.Bitmap
            Get
                Dim obj As Object = DevExpress.RealtorWorld.Win.Properties.Resources.ResourceManager.GetObject("zillow_logo", DevExpress.RealtorWorld.Win.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
